### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by thombergs** [silasmahler/eureka-prometheus-bridge#8]
add a Travis CI pipeline that build the app, runs the tests and automatically deploys the JAR and the docker file to the adesso organization on Bintray.

**Comment by silasmahler** [comment]
Wonderful Tutorial by [Techdev.io](https://techdev.io/de/developer-blog/how-to-publish-a-kotlin-library-to-bintray-using-gradle-and-travis-ci)
CI-Pipeline and [Bintray](https://bintray.com/silasmahler/eureka-prometheus-bridge/eureka-prometheus-bridge/0.0.1) integration is finished, but needs to be transferred to the adessoAG.
The Dockerfile is just for testing and not running the app, so it isnt published to bintray. This is due to the nature of docker that there cant be any dynamic port openings at runtime which the app would need if the configuration changes.
